clippy::unwrap_used = "deny"
clippy::expect_used = "deny"
clippy::panic = "deny"
clippy::result_unwrap_used = "deny"
clippy::option_unwrap_used = "deny"
clippy::explicit_deref_methods = "warn"
clippy::redundant_clone = "warn"
clippy::needless_borrow = "warn"
clippy::borrow_as_ptr = "warn"
clippy::inefficient_to_string = "warn"
clippy::string_to_string = "warn"
clippy::format_push_string = "warn"
