[workspace]
resolver = "2"
members = [
    "crates/blink-core",
    "crates/blink-proto",
    "crates/blink-gdext",
    "crates/blink-cli",
]

[workspace.dependencies]
thiserror = "1.0"
prost = "0.13"
prost-types = "0.13"
tracing = "0.1"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9"
petgraph = "0.6"

[workspace.lints.rust]
unwrap_used = "deny"
expect_used = "deny"
unused_crate_dependencies = "warn"
